version: '3.9'
services:
    ctf:
      container_name: ctf-app
      build: .
      ports:
        - 5000:5000
      environment:
        DEBUG: TRUE
        DBUSER: postgres
        DBPASSWORD: postgres
        DBNAME: postgres
        DBHOST: postgres
        DBPORT: 5432
      depends_on:
        - postgres
      networks:
        - ctf
    postgres:
      container_name: "ctf-psql"
      image: postgres:latest
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      ports:
        - '5432:5432'
      volumes:
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      networks:
        - ctf

networks:
  ctf:
    driver: bridge